/**
 The in-app changelog: renders the build-time-baked CHANGELOG.md
 (`ChangelogData.markdown`, generated by `make changelog`) as one expandable
 glass card per version. The latest (first in the file) starts expanded.
 */
import SwiftUI
import iUXiOS

struct ChangelogView: View {
    var body: some View {
        ScrollView {
            VStack(spacing: 12) {
                ForEach(Self.parse()) { version in
                    ChangelogCard(version: version, isLatest: version.id == 0)
                }
            }
            .padding(16)
        }
        .scrollIndicators(.hidden)
        .navigationTitle("Changelog")
        .navigationBarTitleDisplayMode(.inline)
        .background {
            AmbientBackdrop(tint: .accentColor).ignoresSafeArea()
        }
    }

    /// Split the baked markdown into version sections at each level-2 heading.
    /// The top "# Changelog" + intro paragraph sits before the first one and is
    /// intentionally dropped.
    static func parse() -> [ChangelogVersion] {
        var out: [ChangelogVersion] = []
        var title: String?
        var body: [String] = []
        func flush() {
            if let title { out.append(.init(id: out.count, title: title, bodyLines: body)) }
            body = []
        }
        for raw in ChangelogData.markdown.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(raw)
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("## ") {
                flush()
                title = String(trimmed.dropFirst(3))
                    .replacingOccurrences(of: "[", with: "")
                    .replacingOccurrences(of: "]", with: "")
            } else if title != nil {
                body.append(line)
            }
        }
        flush()
        return out
    }
}

/// One parsed version section — its header (`## [0.1.0] - date`) plus the body
/// lines up to the next version header.
struct ChangelogVersion: Identifiable {
    let id: Int
    /// Display title with the markdown brackets stripped, e.g. "0.1.0 - Unreleased".
    let title: String
    let bodyLines: [String]
}

/// A single expandable version card. CHANGELOG.md hard-wraps its bullets across
/// several source lines, so the parser *reflows* continuation lines back into
/// their bullet/paragraph before rendering; `AttributedString(markdown:)` styles
/// inline **bold** / `code` / links.
private struct ChangelogCard: View {
    let version: ChangelogVersion
    let isLatest: Bool
    @State private var expanded: Bool

    init(version: ChangelogVersion, isLatest: Bool) {
        self.version = version
        self.isLatest = isLatest
        _expanded = State(initialValue: isLatest)
    }

    private enum Block {
        case section(String)              // "Added" / "Fixed" / …
        case bullet(AttributedString)
        case paragraph(AttributedString)
    }

    /// Reflow the hard-wrapped markdown body into logical blocks. A line that is
    /// neither blank, a `###` section, nor a new `- ` bullet is a wrapped
    /// continuation and gets appended to whatever block is open.
    private var blocks: [Block] {
        var out: [Block] = []
        var buf: String?
        var bufIsBullet = false
        func flush() {
            guard let t = buf else { return }
            out.append(bufIsBullet ? .bullet(inline(t)) : .paragraph(inline(t)))
            buf = nil
        }
        for line in version.bodyLines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { flush(); continue }
            if trimmed.hasPrefix("### ") {
                flush(); out.append(.section(String(trimmed.dropFirst(4)))); continue
            }
            if trimmed.hasPrefix("- ") || trimmed.hasPrefix("* ") {
                flush(); buf = String(trimmed.dropFirst(2)); bufIsBullet = true; continue
            }
            if buf != nil { buf! += " " + trimmed }
            else { buf = trimmed; bufIsBullet = false }
        }
        flush()
        return out
    }

    private func inline(_ s: String) -> AttributedString {
        (try? AttributedString(
            markdown: s,
            options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)
        )) ?? AttributedString(s)
    }

    /// "0.1.0 - Unreleased" → ("0.1.0", "Unreleased").
    private var versionParts: (number: String, date: String?) {
        let parts = version.title.components(separatedBy: " - ")
        return (parts.first ?? version.title, parts.count > 1 ? parts[1] : nil)
    }

    private func sectionColor(_ name: String) -> Color {
        switch name.lowercased() {
        case "added":            .green
        case "changed":          .blue
        case "fixed":            .orange
        case let s where s.hasPrefix("security"): .purple
        case "removed", "deprecated": .red
        default:                 .secondary
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header
            if expanded {
                Divider().opacity(0.5).padding(.vertical, 4)
                content
            }
        }
        .padding(16)
        .glassCard(tint: isLatest ? .accentColor : nil)
    }

    private var header: some View {
        Button {
            withAnimation(.snappy(duration: 0.28)) { expanded.toggle() }
        } label: {
            HStack(spacing: 8) {
                Text(versionParts.number)
                    .font(.headline)
                    .foregroundStyle(.primary)
                if let date = versionParts.date {
                    Text(date)
                        .font(.caption.weight(.medium))
                        .foregroundStyle(.secondary)
                }
                if isLatest {
                    Text("LATEST")
                        .font(.caption2.weight(.bold))
                        .tracking(0.5)
                        .foregroundStyle(.white)
                        .padding(.horizontal, 7)
                        .padding(.vertical, 3)
                        .background(Capsule().fill(.tint))
                }
                Spacer()
                Image(systemName: "chevron.down")
                    .font(.caption.weight(.bold))
                    .foregroundStyle(.secondary)
                    .rotationEffect(.degrees(expanded ? 0 : -90))
            }
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }

    private var content: some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(Array(blocks.enumerated()), id: \.offset) { _, block in
                switch block {
                case .section(let name):
                    Text(name.uppercased())
                        .font(.caption.weight(.bold))
                        .tracking(0.5)
                        .foregroundStyle(sectionColor(name))
                        .padding(.top, 4)
                case .bullet(let text):
                    HStack(alignment: .firstTextBaseline, spacing: 8) {
                        Circle().fill(.secondary).frame(width: 4, height: 4)
                            .offset(y: -2)
                        Text(text)
                            .font(.subheadline)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                case .paragraph(let text):
                    Text(text)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}
