#!/usr/bin/env swift
// Bakes ROADMAP.md into a Swift source file for Settings → Roadmap.
// Run by `make roadmap`; `build*` targets list the output as a prerequisite.
//
//   swift Tools/GenerateRoadmap.swift

import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let srcURL = root.appendingPathComponent("ROADMAP.md")
let outURL = root.appendingPathComponent("Sources/Aware/Roadmap.generated.swift")

guard let markdown = try? String(contentsOf: srcURL, encoding: .utf8) else {
    FileHandle.standardError.write(Data("GenerateRoadmap: cannot read \(srcURL.path)\n".utf8))
    exit(1)
}

guard !markdown.contains("\"\"\"#") else {
    FileHandle.standardError.write(Data("GenerateRoadmap: ROADMAP.md contains the raw-string terminator \"\"\"# — bump the delimiter.\n".utf8))
    exit(1)
}

let trimmed = markdown.trimmingCharacters(in: .whitespacesAndNewlines)

let out = """
// Generated by `make roadmap` from ROADMAP.md — do not edit by hand.
// Re-run `make roadmap` (or any `make build*` target) after editing the source.

enum RoadmapData {
    /// The full ROADMAP.md, baked in at build time. Rendered by Settings → Roadmap.
    static let markdown = #\"\"\"
\(trimmed)
\"\"\"#
}

"""

do {
    try out.write(to: outURL, atomically: true, encoding: .utf8)
    print("GenerateRoadmap: wrote \(outURL.path) (\(trimmed.count) chars)")
} catch {
    FileHandle.standardError.write(Data("GenerateRoadmap: cannot write \(outURL.path): \(error)\n".utf8))
    exit(1)
}
